---
- include_vars: "{{ ansible_os_family }}.yml"

- include: "setup-{{ ansible_os_family }}.yml"

- name: Attempting to overlay privoxy configurations
  tags: privoxy
  template:
    src: config.j2
    dest: "{{ privoxy_confdir }}/config"
    owner: "{{ privoxy_user }}"
    group: "{{ privoxy_group }}"
    mode: 0640
...
