---
- name: Ensure that the privoxy package is installed
  tags: privoxy
  homebrew:
    name: privoxy
    state: present

- name: Attempting to overlay privoxy configurations
  tags: privoxy
  template:
    src: config.j2
    dest: "{{ privoxy_confdir }}/config"
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: 0640
...
