---
- name: Ensure that the privoxy package is installed
  tags: privoxy
  homebrew:
    name: privoxy
    state: present
  register: privoxy_homebrew

- name: Attempting to overlay privoxy configurations
  tags: privoxy
  template:
    src: config.j2
    dest: /usr/local/etc/privoxy/config
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: 0640
  when: privoxy_homebrew is success
...
